### ISSUE TITLE
Derive metadata from models

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#107]
Currently, most metadata supplied to services is manually managed; this is due, in part, to the fact that models only load on demand. We should consider returning a usage string derived from available models, but this will require auto-loading all models, which will slow startup time.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/428
