### ISSUE TITLE
MFD Plotter

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#108]
Create an MFD plotter to further support source model mining, and to support enhancements down the road to the fault source parameter dB pages. This requires backfilling source ID's consistent with fault source param dB tables and the ability to collapse logic-tree branch MFDs to a total MFD.

See also usgs/nshmp-haz#287

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/427
