### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz-ws#13]
On main tomcat page for webapp... http://host:port/nshmp-haz-ws/

Returns HTML describing the "HazardCurve" endpoint. This has been renamed to "hazard". Also add documentation for deaggregation.

The "syntax" usage described on the endpoint documentation page also suggests "HazardCurve", which breaks. Similarly, the syntax usage described on the "deagg" endpoint seems to refer to "Deagg" instead. This should all be consistent.

**Comment by pmpowers-usgs** [comment]
This was resolved in #14
