### ISSUE TITLE
Improve range checking and error handling/reporting

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#139]
Currently older GMMs that only support `vs30=[760, 2000]` throw server side errors when a different vs30 is selected. Need to determine if graceful failure is handled on the client or server.

**Comment by bclayton-usgs** [comment]
Error handling is now done in JavaScript to handle any web service returns with `"status" == "error"`, see pr #145. With this update an overlay is display with the error message and the plot is cleared. However, there could be further handling on the server side, e.g reporting which GMMs can support what vs30. If the client side error handling is satisfactory this issue can be closed.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/426
