### ISSUE TITLE
Change "Mode (largest ε₀ bin)" name to "Mode (largest r-m-ε₀ bin)"

### ISSUE THREAD

**Issue by nluco-usgs** [usgs/nshmp-haz-ws#140]
In addition to changing ...

"Mode (largest ε₀ bin)" --> "Mode (largest r-m-ε₀ bin)"

... consider changing ...

"Mean (for all sources)" --> "Mean (across all sources)"

"Mode (largest r-m bin)" --> "Mode (largest m-r bin)"

"Mode (largest r-m-ε₀ bin)" --> "Mode (largest m-r-ε₀ bin)"

**Comment by pmpowers-usgs** [comment]
Using "Mean (_over_ all sources)" instead

**Comment by pmpowers-usgs** [comment]
Resolved in usgs/nshmp-haz#331
