### ISSUE TITLE
Rearrange constraints

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#153]
Currently the UHT and other services assemble `vs30` and `IMT` constraints using the intersections of hard coded arrays in the `Region` and `Edition` enums. In fact, supported `vs30` and `IMT` are a function of model region and year by virtue of the GMMs used.

In the near-term to support #152 we'll add exact arrays to the `Model` enum. Down the road, we should fetch UHT `Edition` constraints from `Model`, and `Model` should ultimately be able to derive metadata from installed models. This comes with it's own issues in as much as all models would have to be pre-loaded to be able to dynamically determine constraints, of constraint metadata would need to be included in the root of the model directory.

Another consideration: Whereas supported `vs30` can be discrete values, and will continue to be  for static datasets, it is more recently and commonly a range.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/423
