### ISSUE TITLE
Update web apps to use new d3 package

### ISSUE THREAD

**Issue by bclayton-usgs** [usgs/nshmp-haz-ws#178]
Update the following web apps to use the new d3 package:

- [x] Dynamic model comparison
- [x] Response spectra
- [x] Ground motion vs. distance
- [x] Hanging wall effects
- [x] Model comparison
- [x] Model Explorer

**Comment by pmpowers-usgs** [comment]
At some point, disable the selection animation when clicking legend entries or plot curves.

**Comment by bclayton-usgs** [comment]
Selections animation is disabled as of #189
