### ISSUE TITLE
Restrict dynamic calculation bounds

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#216]
Dynamic UHT calculations return results outside the bounds where static curves are calculated and can therefore give a very incomplete hazard results for sites (e.g. northwest Bahamas) towards the edges of our rectangular/mercator map regions.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/420
