### ISSUE TITLE
Handle updates to vs30-siteClass values

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#24]
Should we handle SiteClass instead of Vs30, or just both (parse number --> parse enum)?

Sanaz's updated values (adapted from Kircher):
1080      760     530     365     260      185 (m/s)

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/434
