### ISSUE TITLE
CORS Headers

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz-ws#29]
Currently it appear the CORS headers are configured to use the defaults (which is to allow everything). This is okay by me, but the issue I'm having is while the header configuration for allowed origins is "*", the actual header value returned mirrors that of the request referrer host/protocol/port.

The issue with this is that in practice these responses are cached (headers and all) and we do not vary on the access-control-allow-origins header. In this way requests from different referrers for the same resources may causes XHR requests to fail as the returned allowed origin header may not match the request referrer header when the XHR is served by a cached response.

This is unlikely to often affect public requests unless web service requests become popular with external developers. This will affect developers regularly.

**Comment by pmpowers-usgs** [comment]
It is becoming increasingly clear that web service requests are going to be quite popular.

**Comment by pmpowers-usgs** [comment]
These are the headers that are probably needed (example below for node.js, not java:
 * `res.setHeader('Access-Control-Allow-Origin', '*');`
 * `res.setHeader('Access-Control-Allow-Methods', '*');`
 * `res.setHeader('Access-Control-Allow-Headers', 'accept,origin,authorization,content-type');`
