### ISSUE TITLE
Update IMT labels

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/nshmp-haz-ws#33]
Currently they are displayed as:
  - "Peak ground acceleration"
  - "0.2 sec spectral acceleration"
  - "1.0 sec spectral acceleration"

For consistency, these should be:
  - "Peak Ground Acceleration"
  - "0.20 Second Spectral Acceleration"
  - "1.00 Second Spectral Acceleration"

Similar updates for other periods, currently only these three are supported... (?)

**Comment by pmpowers-usgs** [comment]
Can we use the SI unit 's'?
