### ISSUE TITLE
Address zip exceptions

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#34]
Currently when deploying a packed WAR file to dev and prod systems, a zip error occurs (see trace below). It's not clear what changed to cause this to start occurring.

One possible solution is to not pack the models in zip files during a build (ant: zipfileset); there's no real benefit to doing so.

com.google.common.util.concurrent.UncheckedExecutionException: com.google.gson.JsonIOException: java.util.zip.ZipException: invalid stored block lengths (see logs)
...
java.util.concurrent.ExecutionException: 
com.google.common.util.concurrent.UncheckedExecutionException: com.google.gson.JsonIOException: java.util.zip.ZipException: invalid stored block lengths
...
org.opensha2.eq.model.ModelConfig$Builder.fromFile(ModelConfig.java:140)
org.opensha2.eq.model.Loader.load(Loader.java:90) org.opensha2.eq.model.HazardModel.load(HazardModel.java:86)
gov.usgs.earthquake.nshm.www.ServletUtil.loadModel(ServletUtil.java:156) gov.usgs.earthquake.nshm.www.ServletUtil.access$000(ServletUtil.java:49) gov.usgs.earthquake.nshm.www.ServletUtil$1.load(ServletUtil.java:97) gov.usgs.earthquake.nshm.www.ServletUtil$1.load(ServletUtil.java:94)

**Comment by pmpowers-usgs** [comment]
The `<zipfilset />` instruction in this case is just a fancy `<fileset />` instruction that permits use of the 'prefix' attribute; it doesn't actually zip the models that are included in the WAR.

I tested deploying with ` @unpackWars=false` but was not able to replicate the error. Searches for the string 'invalid stored block lengths' suggest that character encoding _may_ be the culprit. Everything on the development side is, or at least should be, UTF-8.

**Comment by pmpowers-usgs** [comment]
For inclusion with this issue: there is no demonstrated need for models to be in zip format; while it may have seemed convenient early on, no one is using this functionality and ultimately it’s easier to have the models be in human readable ascii xml format. The models are effectively zipped when creating a war file in any event.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/433
