### ISSUE TITLE
Allow vs30 values to pass through services

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#54]
For consistency in the earthquake-hazard-tool, nshmp-haz-ws specifies finite vs30 values that each model supports. In regions like the WUS, there is a strong demand to use values outside those specified.

If `region==WUS`, allow any vs30 between min and max to pass through despite not matching a metadata Vs30 enum value.

**Comment by pmpowers-usgs** [comment]
In addition, metadata will need to to supply the vs30 values used to represent eachNEHRP site class, for each Edition.

**Comment by bclayton-usgs** [comment]
Moved to https://code.usgs.gov/ghsc/nshmp/nshmp-haz-v2/issues/431
