### ISSUE TITLE
Create ground motion v. distance plotter and associated web-service

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#80]
Application assumes a vertical strike slip fault, normal to the line of section. Will work similar to spectra plot. Requirements:

* As with spectra-plot, multiple GMMs may be selected
* Comment out (starting from spectra-plot):
  * Event Parameters EXCEPT Mw; other parameters fixed and sent to service for now
  * Path parameters (these will not be sent to service in lieu of rMin = 0, rMax = 300 fixed and hidden)
  * Source Geometry (these WILL be sent to service)

There are two possible variants of this tool that can be developed from the base case above:
* Support multiple magnitudes
* Support multiple Vs30

Further to the above, there is a variant that plots the fault below the data and permits studying geometric and hanging wall effects.

**Comment by bclayton-usgs** [comment]
This has been completed:

usgs/nshmp-haz-ws#81
usgs/nshmp-haz#283
