### ISSUE TITLE
Restructure htdocs

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#93]
The webapp directory is filling up and will continue to do so. We might consider moving all html files and supporting folders down into an apps directory. There would only need to be index.html in the web app directory. Alternatively it may be possible to specify:

```XML
	<welcome-file-list>
		<welcome-file>apps/index.html</welcome-file>
	</welcome-file-list>
```
and keep all html in the apps directory, but I'm not sure if the above will work.

**Comment by bclayton-usgs** [comment]
See pull request #96

**Comment by pmpowers-usgs** [comment]
Oops...

```
webapp/
     apps/
          *.html
          img/
          css/
          js/
```
