### ISSUE TITLE
Rename and update index and dashboard pages

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz-ws#94]
Rename:
* index.html --> services.html
* dashboard.html --> index.html

Add panel to dashboard pointing to the services documentation page.
Consider if/how to merge other application documentation. 
Update header (and footer?) on index page to match

**Comment by bclayton-usgs** [comment]
- Partially resolved in pull request #96.
- Still need to create a panel for services.html
- Header now matches in services.html 
- Should we add the footer as well?

**Comment by pmpowers-usgs** [comment]
I don't think the footer is needed.

**Comment by bclayton-usgs** [comment]
- index.html has been moved back to the root
- A services panel has been added with just a screenshot of the services page

Notes: The screenshot is not the best solution as it is low resolution. We should discuss further the dashboard and find a more permanent solution for the icons.

**Comment by pmpowers-usgs** [comment]
Resolved in #96
